version: '2'
services:
    jhipstercdm-app:
        image: jhipstercdm
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://jhipstercdm-mariadb:3306/jhipstercdm
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 2018:2018
    jhipstercdm-mariadb:
        extends:
            file: mariadb.yml
            service: jhipstercdm-mariadb
